<div class="panel panel-default">
	<table class="table table-striped">
		<thead>
			<tr>
				<th style="width:50px">Edit</th><!--changes to save button after edit mode is activated-->
				<th style="width:100px">Link ID</th>
				<th style="width:33%">Link Name</th>
				<th>URL</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><a class="glyphicon glyphicon-pencil" href="#"/></td>
				<td>1</td>
				<td>YouTube</td>
				<td>youtube.com/user/modec</td>
			</tr>
			<tr>
				<td><a class="glyphicon glyphicon-pencil" href="#"/></td>
				<td>2</td>
				<td>@modec</td>
				<td>twitter.com/modec</td>
			</tr>
			<tr>
				<td><a class="glyphicon glyphicon-pencil" href="#"/></td>
				<td>3</td>
				<td>FaceBook</td>
				<td>facebook.com/modec</td>
			</tr>
		</tbody>
	</table>
</div>