<div class="panel panel-default">
	<table class="table table-striped">
		<thead>
			<tr>
				<th style="width:50px">Edit</th><!--changes to save button after edit mode is activated-->
				<th style="width:100px">Resource ID</th>
				<th style="width:33%">Resource Name</th>
				<th>Other Columns</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><a class="glyphicon glyphicon-pencil" href="#"/></td>
				<td>3</td>
				<td>Still_Confused</td>
				<td>stuff</td>
			</tr>
			<tr>
				<td><a class="glyphicon glyphicon-pencil" href="#"/></td>
				<td>5</td>
				<td>Register</td>
				<td>unsure</td>
			</tr>
			<tr>
				<td><a class="glyphicon glyphicon-pencil" href="#"/></td>
				<td>6</td>
				<td>Need</td>
				<td>data</td>
			</tr>
		</tbody>
	</table>
</div>