<div class="panel panel-default">
	<table class="table table-striped">
		<thead>
			<tr>
				<th style="width:50px">Edit</th><!--changes to save button after edit mode is activated-->
				<th>Route ID</th>
				<th>Label</th>
				<th>Route</th>
				<th>Parameters</th>
				<th>URI</th>
				<th>Resource</th>
				<th>Privilege</th>
				<th>Menu</th>
				<th>Order</th>
				<th>Parent</th>
				<th>Module</th>
				<th>Active</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><a class="glyphicon glyphicon-pencil" href="#"/></td>
				<td>3</td>
				<td>Home</td>
				<td>home</td>
				<td>NULL</td>
				<td>NULL</td>
				<td>NULL</td>
				<td>NULL</td>
				<td>primary</td>
				<td>100</td>
				<td>NULL</td>
				<td>Core</td>
				<td>True</td>
			</tr>
			<tr>
				<td><a class="glyphicon glyphicon-pencil" href="#"/></td>
				<td>5</td>
				<td>Register</td>
				<td>register</td>
				<td>NULL</td>
				<td>NULL</td>
				<td>auth</td>
				<td>register</td>
				<td>secondary</td>
				<td>100</td>
				<td>NULL</td>
				<td>Core</td>
				<td>True</td>
			</tr>
			<tr>
				<td><a class="glyphicon glyphicon-pencil" href="#"/></td>
				<td>6</td>
				<td>Login</td>
				<td>login</td>
				<td>NULL</td>
				<td>NULL</td>
				<td>auth</td>
				<td>login</td>
				<td>secondary</td>
				<td>200</td>
				<td>NULL</td>
				<td>Core</td>
				<td>True</td>
			</tr>
		</tbody>
	</table>
</div>