<div class="panel panel-default">
	<table class="table table-striped">
		<thead>
			<tr>
				<th style="width:100px">Setting ID</th>
				<th style="width:25%">Setting Name</th>
				<th style="width:33%">Setting Description</th>
				<th>Value</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>1</td>
				<td>GallerySize</td>
				<td>limit to number of photos per user</td>
				<td><input type="text" value="100"/></td>
			</tr>
			<tr>
				<td>2</td>
				<td>BlogLength</td>
				<td>max length for a blog post</td>
				<td><input type="text" value="255"/></td>
			</tr>
			<tr>
				<td>3</td>
				<td>RequireLogin</td>
				<td>require login to view pages</td>
				<td><input type="text" value="False"/></td>
			</tr>
		</tbody>
	</table>
</div>
<button style="position:relative; left:40%">Save Changes</button>