<div data-example-id="panel-without-body-with-table" class="bs-example">
	<div class="panel panel-default">
		<div class="panel-heading">
		
		<form role="search" style="float: right;">
			<input type="text" placeholder="Search Username" class="form-control" style="height: 30px; margin-top: -5px;" />
		</form>
		
			Browse Users
		</div>
		<table class="table table-striped">
			<thead>
				<tr>
					<th style="text-align: right; width: 75px;">User ID</th>
					<th>Username</th>
					<th style="text-align: right">Usergroup</th>
				</tr>
			</thead>
			<tbody>
				<?php $i = 20; ?>
				<?php while($i-- > 0): ?>
					<tr>
						<th scope="row" style="text-align: right">#</th>
						<td><a href="#">Username</a></td>
						<td style="text-align: right">Usergroup</td>
					</tr>
				<?php endwhile; ?>
			</tbody>
		</table>
	</div>
</div>

<nav style="text-align: center;">
	<ul class="pagination" style="margin: 0px 0px 10px;">
		<li>
			<a href="#" aria-label="Previous">
			<span aria-hidden="true">&laquo;</span>
			</a>
		</li>
		<li class="active"><a href="#">1</a></li>
		<li><a href="#">2</a></li>
		<li><a href="#">3</a></li>
		<li><a href="#">4</a></li>
		<li><a href="#">5</a></li>
		<li>
			<a href="#" aria-label="Next">
			<span aria-hidden="true">&raquo;</span>
			</a>
		</li>
	</ul>
</nav>




<!--
<div class="panel-group">
	<div class="panel panel-default">
		<div class="panel-heading" data-toggle="collapse" data-target="#collapse0">
			<div class="container-fluid panel-container">
				<h4 class="panel-title col-xs-6 text-left">
					0 : Alice
				</h4>
				<div class="col-xs-6 text-right"/>
					<span class="panel-title btn-group">
						<a class="glyphicon glyphicon-pencil" href="#"></a>
						<a class="glyphicon glyphicon-ban-circle" href="#0"></a>
					</span>
				</div>
			</div>
		</div>
		<div id="collapse0" class="panel-collapse collapse">
			<li class="list-group-item">ID: 0</li>
			<li class="list-group-item">Username: Alice</li>
			<li class="list-group-item">Email: alice@test.net</li>
			<li class="list-group-item">
				<button class="btn">Change Password</button>
				<button class="btn">Save Changes</button>
			</li>
		</div>
	</div>
	<div class="panel panel-default">
		<div class="panel-heading" data-toggle="collapse" data-target="#collapse1">
			<div class="container-fluid panel-container">
				<h4 class="panel-title col-xs-6 text-left">
					1 : Bob
				</h4>
				<div class="col-xs-6 text-right"/>
					<span class="panel-title btn-group">
						<a class="glyphicon glyphicon-pencil" href="#"></a>
						<a class="glyphicon glyphicon-ban-circle" href="#1"></a>
					</span>
				</div>
			</div>
		</div>
		<div id="collapse1" class="panel-collapse collapse">
			<li class="list-group-item">ID: 1</li>
			<li class="list-group-item">Username: Bob</li>
			<li class="list-group-item">Email: bob@test.net</li>
			<li class="list-group-item">
				<button class="btn">Change Password</button>
				<button class="btn">Save Changes</button>
			</li>
		</div>
	</div>
</div>
-->
