<?php
	// Add the head title
	$this->headTitle('Register');

	// Add the page css
	$this->headLink()->prependStylesheet($this->basePath('css/register.css'));

	// Customize the form
	$this->form->setAttribute('class', 'form-horizontal');

	$this->formElementErrors()->setMessageOpenFormat('<span class="help-block">');
	$this->formElementErrors()->setMessageSeparatorString('</span><span class="help-block">');
	$this->formElementErrors()->setMessageCloseString('</span>');

	$this->form->get('username')->setAttribute('class', 'form-control');
    $this->form->get('username')->setLabelAttributes(array(
		'class' => 'col-sm-2 control-label'
	));

	$this->form->get('email')->setAttribute('class', 'form-control');
    $this->form->get('email')->setLabelAttributes(array(
		'class' => 'col-sm-2 control-label'
	));

	$this->form->get('email_confirm')->setAttribute('class', 'form-control');
    $this->form->get('email_confirm')->setLabelAttributes(array(
		'class' => 'col-sm-2 control-label'
	));

	$this->form->get('password')->setAttribute('class', 'form-control');
    $this->form->get('password')->setLabelAttributes(array(
		'class' => 'col-sm-2 control-label'
	));

	$this->form->get('password_confirm')->setAttribute('class', 'form-control');
    $this->form->get('password_confirm')->setLabelAttributes(array(
		'class' => 'col-sm-2 control-label'
	));

	$this->form->get('captcha')->setAttribute('class', 'form-control');
    $this->form->get('captcha')->setLabelAttributes(array(
		'class' => 'col-sm-2 control-label'
	));

	$this->formCaptchaFiglet()->setSeparator('</div><div class="col-sm-offset-2 col-sm-4">');
	
	$this->form->get('submit')->setAttribute('class', 'btn btn-primary btn-block');
?>

<?php echo $this->form()->openTag($this->form); ?>
	<h1>New User Registration</h1>
	<div class="form-group <?php echo ($this->formHasErrors($this->form->get('username')) ? 'has-error' : ''); ?>">
		<?php echo $this->formLabel($this->form->get('username')); ?>
		<div class="col-sm-4">
			<?php echo $this->formElement($this->form->get('username')); ?>
			<?php echo $this->formElementErrors($this->form->get('username')); ?>
		</div>
	</div>
	<div class="form-group">
		<div class="<?php echo ($this->formHasErrors($this->form->get('email')) ? 'has-error' : ''); ?>">
			<?php echo $this->formLabel($this->form->get('email')); ?>
			<div class="col-sm-4">
				<?php echo $this->formElement($this->form->get('email')); ?>
				<?php echo $this->formElementErrors($this->form->get('email')); ?>
			</div>
		</div>
		<div class="<?php echo ($this->formHasErrors($this->form->get('email_confirm')) ? 'has-error' : ''); ?>">
			<?php echo $this->formLabel($this->form->get('email_confirm')); ?>
			<div class="col-sm-4">
				<?php echo $this->formElement($this->form->get('email_confirm')); ?>
				<?php echo $this->formElementErrors($this->form->get('email_confirm')); ?>
			</div>
		</div>
	</div>
	<div class="form-group">
		<div class="<?php echo ($this->formHasErrors($this->form->get('password')) ? 'has-error' : ''); ?>">
			<?php echo $this->formLabel($this->form->get('password')); ?>
			<div class="col-sm-4">
				<?php echo $this->formElement($this->form->get('password')); ?>
				<?php echo $this->formElementErrors($this->form->get('password')); ?>
			</div>
		</div>
		
		<div class="<?php echo ($this->formHasErrors($this->form->get('password_confirm')) ? 'has-error' : ''); ?>">
			<?php echo $this->formLabel($this->form->get('password_confirm')); ?>
			<div class="col-sm-4">
				<?php echo $this->formElement($this->form->get('password_confirm')); ?>
				<?php echo $this->formElementErrors($this->form->get('password_confirm')); ?>
			</div>
		</div>
	</div>
	<div class="form-group <?php echo ($this->formHasErrors($this->form->get('captcha')) ? 'has-error' : ''); ?>">
		<?php echo $this->formLabel($this->form->get('captcha')); ?>
		<div class="col-sm-10">
			<?php echo $this->formCaptchaFiglet($this->form->get('captcha')); ?>
			<?php echo $this->formElementErrors($this->form->get('captcha')); ?>
		</div>
		<div class="col-sm-6">
			<span class="help-block captcha-help">Please input the displayed text here.</span>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-offset-3 col-sm-6">
			<?php echo $this->formSubmit($this->form->get('submit')); ?>
		</div>
	</div>
<?php echo $this->form()->closeTag(); ?>
