<div class="navbar navbar-default">
	<div class="navbar-inner">
		<ul class="nav navbar-nav">
			<li id="0"><a href='/admin/index'>Dashboard</a></li>
			<li id="1"><a href='/admin/users'>Users</a></li>
			<li id="2"><a href='/admin/routes'>Routes</a></li>
			<li id="3"><a href='/admin/settings'>Site Settings</a></li>
			<li id="4"><a href='/admin/resources'>Resource Permissions</a></li>
			<li id="5"><a href='/admin/links'>Links</a></li>
		</ul>
	</div>
</div>