<?php include('adminWrapper.phtml'); ?>
<div class="panel-group">
	<div class="panel panel-default">
		<div class="panel-heading" data-toggle="collapse" data-target="#collapse0">
			<div class="container-fluid panel-container">
				<h4 class="panel-title col-xs-6 text-left">
					0 : Alice
				</h4>
				<div class="col-xs-6 text-right"/>
					<span class="panel-title btn-group">
						<a class="glyphicon glyphicon-pencil" href="#"></a>
						<a class="glyphicon glyphicon-ban-circle" href="#0"></a>
					</span>
				</div>
			</div>
		</div>
		<div id="collapse0" class="panel-collapse collapse">
			<li class="list-group-item">ID: 0</li>
			<li class="list-group-item">Username: Alice</li>
			<li class="list-group-item">Email: alice@test.net</li>
			<li class="list-group-item">
				<button class="btn">Change Password</button>
				<button class="btn">Save Changes</button>
			</li>
		</div>
	</div>
	<div class="panel panel-default">
		<div class="panel-heading" data-toggle="collapse" data-target="#collapse1">
			<div class="container-fluid panel-container">
				<h4 class="panel-title col-xs-6 text-left">
					1 : Bob
				</h4>
				<div class="col-xs-6 text-right"/>
					<span class="panel-title btn-group">
						<a class="glyphicon glyphicon-pencil" href="#"></a>
						<a class="glyphicon glyphicon-ban-circle" href="#1"></a>
					</span>
				</div>
			</div>
		</div>
		<div id="collapse1" class="panel-collapse collapse">
			<li class="list-group-item">ID: 1</li>
			<li class="list-group-item">Username: Bob</li>
			<li class="list-group-item">Email: bob@test.net</li>
			<li class="list-group-item">
				<button class="btn">Change Password</button>
				<button class="btn">Save Changes</button>
			</li>
		</div>
	</div>
</div>