<?php
	// Add the head title
	$this->headTitle('Blog');

	// Add the page css
	$this->headLink()->prependStylesheet($this->basePath('css/blog.css'));
?>

<h1>Blog</h1>

<!-- @todo Handle when there are no posts to display! -->

<?php if ($this->hasPermission('blog', 'add')): ?>
	<a href="<?php echo $this->url('blog/add'); ?>">Add New Post</a>
<?php endif; ?>

<?php foreach ($this->posts as $post): ?>
	<article id="blog-post-<?php echo $post->id; ?>" class="blog-post">
		<h2><?php echo $post->title; ?></h2>
		<div class="post-text">
			<?php echo $post->briefText; ?>
			<a href="<?php echo $this->url('blog/view', $post->getCleanArrayCopy()); ?>">
				<?php if ($post->textExceedsBrief()): ?>
					Read More
				<?php else: ?>
					View Post
				<?php endif; ?>
			</a>
		</div> <br/>
		<div class="byline">
			Posted by <span class="author"><?php echo $post->username; ?></span>
			on <span class="date"><?php echo $this->dateFormat(
				$post->date, IntlDateFormatter::LONG, IntlDateFormatter::SHORT, "en_US"
			); ?></span>
		</div>
	</article>
	<hr /> <!-- @todo This HR should be done as a bottom border on all but the last child elements of the article itself. -->
<?php endforeach ?>
