<?php
	// Add the head title
	$this->headTitle('Blog');

	// Add the page css
	$this->headLink()->prependStylesheet($this->basePath('css/blog.css'));
?>

<article id="blog-post-<?php echo $this->post->id; ?>" class="blog-post">
	<h1><?php echo $this->post->title; ?></h1>
	<div class="post-text">
		<?php echo $this->post->text; ?>
	</div>
	<div class="byline">
		Posted by <span class="author"><?php echo $this->post->username; ?></span> on <span class="date"><?php echo $this->dateFormat(
			$post->date, IntlDateFormatter::LONG, IntlDateFormatter::SHORT, "en_US"
		); ?></span>
	</div>
	<?php if (isset($post->editDate)): ?>
		<div class="editline">
			Last edited by <span class="author"><?php echo $this->post->editUsername; ?></span> on <span class="date"><?php echo $this->dateFormat(
				$post->editDate, IntlDateFormatter::LONG, IntlDateFormatter::SHORT, "en_US"
			); ?></span>
		</div>
	<?php endif; ?>
	<?php if (true || $this->hasPermission('blog', 'edit') || $this->hasPermission('blog', 'delete')): ?> <!-- @todo Make the permission helper and fix this! -->
		<ul class="options">
			<?php if (true || $this->hasPermission('blog', 'edit')): ?> <!-- @todo Make the permission helper and fix this! -->
				<li><a href="<?php echo $this->url('blog/edit', $post->getCleanArrayCopy()); ?>">Edit Post</a></li>
			<?php endif; ?>
			<?php if (true || $this->hasPermission('blog', 'delete')): ?> <!-- @todo Make the permission helper and fix this! -->
				<li><a href="<?php echo $this->url('blog/delete', $post->getCleanArrayCopy()); ?>">Delete Post</a></li>
			<?php endif; ?>
		</ul>
	<?php endif; ?>
</article>