 <html> 
 <h1>Blog Module</h1>
 
 <?php  
	foreach ($this->posts as $post): 
?>
 <article>
     <h1 id="post<?= $post->getPostid() ?>"><?= $post->getPosttitle() ?></h1>
     <p>
         <?= $post->getPosttext() ?> <br> 
		 <?php echo "Posted By : " ?> 
		 <?= $post->getUserid() ?> 
		 <?php echo '<br>' . "Posted On : " ?>
		 <?= $post->getDateformat() ?>
     </p>
 </article>
 <?php endforeach ?>  
 </html> 