<?php

$flashMessenger = $this->flashMessenger();
$flashMessenger->setMessageOpenFormat('<div%s><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>')
	->setMessageSeparatorString('</div><div%s><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>')
	->setMessageCloseString('</div>');

echo $flashMessenger->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
echo $flashMessenger->render('success', array('alert', 'alert-dismissible', 'alert-success'));
echo $flashMessenger->render('warning', array('alert', 'alert-dismissible', 'alert-warning'));
echo $flashMessenger->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
echo $flashMessenger->render('default', array('alert', 'alert-dismissible', 'alert-info'));
