<ul class="<?php echo $this->navigation()->menu()->getUlClass() ?>">
	<?php foreach ($this->container as $page):
		if (!$page->isVisible() || !$this->navigation()->accept($page)) { continue; }
	
		$active = $page->isActive();
		$children = $page->getPages();

		if ($children) {
			foreach ($children as $key => $child) {
				if (!$child->isVisible() || !$this->navigation()->accept($child)) {
					unset($children[$key]);
				} else {
					$active = $active || $child->isActive();
				}
			}
		}
		
		$liClass = array();
			if ($active)   { $liClass[] = 'active'; }
			if ($children) { $liClass[] = 'dropdown'; }
		$liClass = implode(' ', $liClass);
	?>
		<li class="<?php echo $liClass; ?>">
			<?php if ($children): ?>			
				<a href="<?php echo $page->getHref() ?>" target="<?php echo $page->getTarget() ?>" class="dropdown-toggle" data-toggle="dropdown">
					<?php echo $page->getLabel() ?>
					<span class="caret"></span>
				</a>
				<ul class="dropdown-menu">
					<?php foreach ($children as $child): ?>
						<li class="<?php echo ($child->isActive() ? 'active' : '') ?>">
							<a href="<?php echo $child->getHref() ?>" target="<?php echo $child->getTarget() ?>">
								<?php echo $child->getLabel() ?>
							</a>
						</li>
					<?php endforeach; ?>
				</ul>
			<?php else: ?>			
				<a href="<?php echo $page->getHref() ?>" target="<?php echo $page->getTarget() ?>">
					<?php echo $page->getLabel() ?>
				</a>
			<?php endif; ?>
		</li>
	<?php endforeach; ?>
</ul>