<div class="alert alert-danger" role="alert">
	<b>Warning!</b> Your site is currently in developer mode!
</div>

<div class="row">
	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Enabled Modules</h3>
			</div>
			<div class="panel-body">
				<ul>
					<?php foreach($modules as $module): ?>
						<li><?php echo $module; ?></li>
					<?php endforeach; ?>
				</ul>
			</div>
		</div>
	</div>
	<div class="col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Statistics</h3>
			</div>
			<div class="panel-body">
				<p>Show some statistics here!</p>
			</div>
		</div>
	</div>
</div>
