<?php echo $this->doctype(); ?>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<?php
			echo $this->headTitle('Modec')->setSeparator(' - ')->setAutoEscape(false);

			echo $this->headMeta()
				->appendName('viewport', 'width=device-width, initial-scale=1.0')
				->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

			$this->headLink(array(
				'rel' => 'shortcut icon',
				'type' => 'image/vnd.microsoft.icon',
				'href' => $this->basePath() . '/img/favicon.ico'
			));
		?>

		<!-- Style -->
        <?php
			echo $this->headLink()
				->prependStylesheet($this->basePath('css/admin.css'))
				->prependStylesheet($this->basePath('css/general.css'))
				->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
				->prependStylesheet($this->basePath('css/bootstrap.min.css'));
		?>
		
		<!-- Script -->		
        <?php
			echo $this->headScript()
				->prependFile($this->basePath('js/general.js'))
				->prependFile($this->basePath('js/bootstrap.min.js'))
				->prependFile($this->basePath('js/jquery.min.js'))
				->prependFile(
					$this->basePath('js/respond.min.js'),
					'text/javascript',
					array('conditional' => 'lt IE 9')
				)
				->prependFile(
					$this->basePath('js/html5shiv.min.js'),
					'text/javascript',
					array('conditional' => 'lt IE 9')
				);
		?>
    </head>
    <body>
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="/">Modec Admin CP</a>
				</div>
				<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav navbar-right">
						<?php if ($user = $this->identity()): ?>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
									<img class="navbar-user-icon" alt="" src="http://images.onlinelabels.com/images/clip-art/acspike/acspike_male_user_icon.png" />
									<?php echo $this->escapeHtml($user->username) ?>
								</a>
								<?php 
									echo $this->navigation('user')
										->menu()
										->setMaxDepth(0)
										->setUlClass('dropdown-menu');
								?>
							</li>
						<?php else: ?>
							<li>
								<a href="<?php echo $this->url('login') ?>">
									<?php echo $this->translate('Login') ?>
								</a>
							</li>
						<?php endif; ?>
					</ul>
                    <?php 
						echo $this->navigation('admin')
							->menu()
							->setMaxDepth(0)
							->setPartial('partial/navigation.phtml')
							->setUlClass('nav navbar-nav');
					?>
				</div>
			</div>
		</nav>
		<div class="container">
			<?php
				$flash = $this->flashMessenger();
				$flash->setMessageOpenFormat('<div%s><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
					->setMessageSeparatorString('</li><li>')
					->setMessageCloseString('</li></ul></div>');				
				
				echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
				echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
				echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
				echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
				
				echo $this->content;
			?>
        </div>
		<footer>
			<div class="container">
				<?php 
					echo $this->navigation('footer')
						->menu()
						->setMaxDepth(0)
						->setUlClass('nav footer-nav');
				?>
				<div class="copyright-text">Copyright &copy; 2016 Team Modec</div>
			</div>
		</footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
