<?php echo $this->doctype(); ?>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<?php
			echo $this->headTitle('Admin CP')->setSeparator(' - ')->setAutoEscape(false);

			echo $this->headMeta()
				->appendName('viewport', 'width=device-width, initial-scale=1.0')
				->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

			$this->headLink(array(
				'rel' => 'shortcut icon',
				'type' => 'image/vnd.microsoft.icon',
				'href' => $this->basePath() . '/img/favicon.ico'
			));
		?>

		<!-- Style -->
        <?php
			echo $this->headLink()
				->prependStylesheet($this->basePath('css/admin.css'))
				->prependStylesheet($this->basePath('css/general.css'))
				->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
				->prependStylesheet($this->basePath('css/bootstrap.min.css'));
		?>
		
		<!-- Script -->		
        <?php
			echo $this->headScript()
				->prependFile($this->basePath('js/general.js'))
				->prependFile($this->basePath('js/bootstrap.min.js'))
				->prependFile($this->basePath('js/jquery.min.js'))
				->prependFile(
					$this->basePath('js/respond.min.js'),
					'text/javascript',
					array('conditional' => 'lt IE 9')
				)
				->prependFile(
					$this->basePath('js/html5shiv.min.js'),
					'text/javascript',
					array('conditional' => 'lt IE 9')
				);
		?>
    </head>
    <body>
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="<?php echo $this->url('admin') ?>">Admin CP</a>
				</div>
				<div class="collapse navbar-collapse">
                    <?php 
						echo $this->navigation('admin')
							->menu()
							->setMaxDepth(0)
							->setPartial('partial/navigation.phtml')
							->setUlClass('nav navbar-nav');
					?>
				</div>
			</div>
		</nav>
		<div class="container">
			<div class="nojs alert alert-warning">
				<strong>Warning!</strong> For the best browsing experience, please enable JavaScript in your browser settings. 
			</div>
			<?php
				$flashMessenger = $this->flashMessenger();
				$flashMessenger->setMessageOpenFormat('<div%s><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>')
					->setMessageSeparatorString('</div><div%s><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>')
					->setMessageCloseString('</div>');
				
				echo $flashMessenger->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
				echo $flashMessenger->render('success', array('alert', 'alert-dismissible', 'alert-success'));
				echo $flashMessenger->render('warning', array('alert', 'alert-dismissible', 'alert-warning'));
				echo $flashMessenger->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
				echo $flashMessenger->render('default', array('alert', 'alert-dismissible', 'alert-info'));
				
				echo $this->content;
			?>
        </div>
		<footer>
			<div class="container">
				<ul class="nav footer-nav">
					<li>
						Logged in as
						<a href="#">
							<?php echo $this->escapeHtml($this->identity()->username) ?>
						</a>
					</li>
					<li>
						<a href="<?php echo $this->url('logout') ?>">
							<?php echo $this->translate('Logout') ?>
						</a>
					</li>
					<li>
						<a href="<?php echo $this->url('home') ?>">
							<?php echo $this->translate('Return to Front End') ?>
						</a>
					</li>
				</ul>
				<div class="copyright-text">Copyright &copy; 2016 Team Modec</div>
			</div>
		</footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
