<?php
	// Add the head title
	$this->headTitle('Photo Gallery');

	// Add the page css
	$this->headLink()->prependStylesheet($this->basePath('css/gallery.css'));

	// Customize the form
	$this->form->setAttribute('class', 'form-horizontal');

	$this->formElementErrors()->setMessageOpenFormat('<span class="help-block">');
	$this->formElementErrors()->setMessageSeparatorString('</span><span class="help-block">');
	$this->formElementErrors()->setMessageCloseString('</span>');

	$this->form->get('content')->setAttribute('class', 'form-control');
    $this->form->get('content')->setLabelAttributes(array(
		'class' => 'col-sm-2 control-label'
	));

	$this->form->get('submit')->setAttribute('class', 'btn btn-primary btn-block');
?>

<?php echo $this->form()->openTag($this->form); ?>
	<h1>Add New Photo Comment</h1>

	<div class="form-group <?php echo ($this->formHasErrors($this->form->get('content')) ? 'has-error' : ''); ?>">
		<?php echo $this->formLabel($this->form->get('content')); ?>
		<div class="col-sm-10">
			<?php echo $this->formElement($this->form->get('content')); ?>
			<?php echo $this->formElementErrors($this->form->get('content')); ?>
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-offset-3 col-sm-6">
			<?php echo $this->formElement($this->form->get('imageid')); ?>
			<?php echo $this->formSubmit($this->form->get('submit')); ?>
		</div>
	</div>
<?php echo $this->form()->closeTag(); ?>
