<?php
 //Gallery: edit photo page
 $title = 'Edit gallery';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'gallery',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('photoId'));
 echo $this->formRow($form->get('userid'));
 echo $this->formHidden($form->get('timestamp'));
 echo $this->formRow($form->get('description'));
 echo $this->formHidden($form->get('location'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();