<?php
	// Add the head title
	$this->headTitle('Photo Gallery');

	// Add the page css
	$this->headLink()->prependStylesheet($this->basePath('css/gallery.css'));
?>

<h1><?php echo $this->image->title; ?></h1>

<img class="img-thumbnail img-responsive center-block" src="<?php echo $this->basePath($image->imageLocation); ?>" alt="<?php echo $image->title; ?>">

<?php if ($this->image->description): ?>
	<div class="image-description">
		<?php echo $this->image->description; ?>
	</div>
<?php endif; ?>

<div class="byline">
	Posted by <span class="author"><?php echo $this->image->username; ?></span>
	on <span class="date"><?php echo $this->dateFormat(
		$image->date, IntlDateFormatter::LONG, IntlDateFormatter::SHORT, "en_US"
	); ?></span>
</div>

<?php if (isset($this->image->editDate)): ?>
	<div class="editline">
		Last edited by <span class="author"><?php echo $this->image->editUsername; ?></span>
		on <span class="date"><?php echo $this->dateFormat(
			$this->image->editDate, IntlDateFormatter::LONG, IntlDateFormatter::SHORT, "en_US"
		); ?></span>
	</div>
<?php endif; ?>

<?php if ($user = $this->identity()): ?>
	<?php
		$canEdit = $this->hasPermission('gallery', 'edit') && (
			$image->userid == $user->userid || $this->hasPermission('gallery', 'edit-others')
		);

		$canDelete = $this->hasPermission('gallery', 'delete') && (
			$image->userid == $user->userid || $this->hasPermission('gallery', 'delete-others')
		);
	?>

	<?php if ($canEdit || $canDelete): ?>
		<ul class="options">
			<?php if ($canEdit): ?>
				<li><a href="<?php echo $this->url('gallery/edit', $image->getCleanArrayCopy()); ?>">Edit Image</a></li>
			<?php endif; ?>
			<?php if ($canDelete): ?>
				<li><a href="<?php echo $this->url('gallery/delete', $image->getCleanArrayCopy()); ?>">Delete Image</a></li>
			<?php endif; ?>
		</ul>
	<?php endif; ?>
<?php endif; ?>

<?php while($comment = $this->comments->current()): ?>
	<?php echo $comment->content ?>
	<?php echo $comment->userid ?>
	<?php echo $comment->date ?>
	<?php $this->comments->next(); ?>
<?php endwhile; ?>
