<?php echo $this->doctype(); ?>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<?php
			echo $this->headTitle('Modec')->setSeparator(' - ')->setAutoEscape(false);

			echo $this->headMeta()
				->appendName('viewport', 'width=device-width, initial-scale=1.0')
				->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

			$this->headLink(array(
				'rel' => 'shortcut icon',
				'type' => 'image/vnd.microsoft.icon',
				'href' => $this->basePath() . '/img/favicon.ico'
			));
		?>

		<!-- Style -->
        <?php
			echo $this->headLink()
				->prependStylesheet($this->basePath('css/general.css'))
				->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
				->prependStylesheet($this->basePath('css/bootstrap.min.css'));
		?>
		
		<!-- Script -->		
        <?php
			echo $this->headScript()
				->prependFile($this->basePath('js/general.js'))
				->prependFile($this->basePath('js/bootstrap.min.js'))
				->prependFile($this->basePath('js/jquery.min.js'))
				->prependFile(
					$this->basePath('js/respond.min.js'),
					'text/javascript',
					array('conditional' => 'lt IE 9')
				)
				->prependFile(
					$this->basePath('js/html5shiv.min.js'),
					'text/javascript',
					array('conditional' => 'lt IE 9')
				);
		?>
    </head>
    <body>
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="<?php echo $this->url('home') ?>">Modec</a>
				</div>
				<div class="collapse navbar-collapse">
					<?php if ($user = $this->identity()): ?>
						<ul class="nav navbar-nav navbar-right">
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
									<img class="navbar-user-icon" alt="" src="/img/user-icon.png" />
									<?php echo $this->escapeHtml($user->username) ?>
								</a>
								<?php 
									echo $this->navigation('user')
										->menu()
										->setPartial(null)
										->setUlClass('dropdown-menu');
								?>
							</li>
						</ul>
					<?php endif; ?>
                    <?php 
						echo $this->navigation('primary')
							->menu()
							->setPartial('global/navigation.phtml')
							->setUlClass('nav navbar-nav');

						echo $this->navigation('secondary')
							->menu()
							->setPartial('global/navigation.phtml')
							->setUlClass('nav navbar-nav navbar-right');
					?>
				</div>
			</div>
		</nav>
		<div class="container">
			<noscript>
				<div class="alert alert-warning">
					<strong>Warning!</strong> For the best browsing experience, please enable JavaScript in your browser settings. 
				</div>
			</noscript>
			<?php
				echo $this->partial('global/flashMessenger');

				echo $this->navigation('primary')
					->breadcrumbs()
					->setMinDepth(1)
					->setPartial('global/breadcrumb.phtml');
 
				echo $this->content;
			?>
        </div>
		<footer>
			<div class="container">
				<?php 
					echo $this->navigation('footer')
						->menu()
						->setPartial(null)
						->setUlClass('nav footer-nav');
				?>
				<div class="copyright-text">Copyright &copy; 2016 Team Modec</div>
			</div>
		</footer>
        <?php echo $this->inlineScript(); ?>
    </body>
</html>
