 <p>
     Are you sure that you want to delete
     '<?php echo $this->escapeHtml($this->post->getPosttitle()); ?>' by
     '<?php echo $this->escapeHtml($this->post->getPosttext()); ?>'?
 </p>
 <form action="<?php echo $this->url('blog/deletepost', array(), true) ?>" method="post">
     <input type="submit" name="delete_confirmation" value="yes">
     <input type="submit" name="delete_confirmation" value="no">
 </form>