<!--Create user page-->
<?php 
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
    </button>
    <ul><li>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
?>
<div class="row">
    <div class="col-md-6">
		<h1>New User</h1>
		<?php 
			$form = $this->createForm;
			$form->prepare();
			echo $this->form()->openTag($form);
			echo $this->formlabel($form->get('username'));
			echo $this->formElement($form->get('username')); 
		?>
		<span class="common-error-msg"><?php echo $this->formElementErrors($form->get('username'));?></span>
		<?php 
			echo $this->formlabel($form->get('password'));
			echo $this->formElement($form->get('password')); 
		?>
		<span class="common-error-msg"><?php echo $this->formElementErrors($form->get('password'));?></span>
		<?php 
			echo $this->formlabel($form->get('repassword'));
			echo $this->formElement($form->get('repassword')); 
		?>
		<span class="common-error-msg"><?php echo $this->formElementErrors($form->get('repassword'));?></span>
		<p/>
		<div> 
			<?php 
				echo $this->formElement($form->get('create'));
				echo ' ';
				echo $this->formElement($form->get('login'));
				echo $this->formRow($form->get('createCsrf'));
				echo $this->form()->closeTag($form);
			?>
		</div>
	</div>
</div>